### ISSUE TITLE
How is init command different than stagehand?

### ISSUE THREAD

**Issue by seaneagan** [google/tuneup.dart#22]

**Comment by devoncarew** [comment]
It creates a tiny helloworld CLI project. Stagehand tends to larger starter examples. That said, this command may be gratuitous, or end up delegating to Stagehand at some point. The `clean` command also doesn't see a lot of use, or add much to what you can do with existing tools.

The `check` and `trim` commands I use quite a bit. `check` because it'll often find issues that `dartanalyzer` misses, and `trim` because it fixes common whitespace nits that would otherwise cause wasted time in code reviews -

**Comment by devoncarew** [comment]
Closing...
