### ISSUE TITLE
add a command to find unused package dependencies

### ISSUE THREAD

**Issue by devoncarew** [google/tuneup.dart#9]

**Comment by travissanderson-wf** [comment]
@devoncarew I'm wondering if this was closed because you decided not to do it, because it is supported now, or because there is something that already does this.  I was thinking about writing something but decided to look for an existing tool and found this!

**Comment by devoncarew** [comment]
I just didn't get to it. I'm not sure if there is another tool that does it; perhaps the `linter` package?

**Comment by travissanderson-wf** [comment]
Looks like it is an outstanding request for linter https://github.com/dart-lang/linter/issues/28.  Do you think it is an equally good fit in either project?

**Comment by travissanderson-wf** [comment]
I have this partially completed in this branch https://github.com/travissanderson-wf/tuneup.dart/tree/depcheck.

For regular dependencies, the only thing I know of that is missing is filtering out transformers that are using `$exclude`/`$include`.

For dev dependencies, in our org we have a weird case due to dart_dev where we list dependencies that are actually only transitive dependencies (like coverage, dart_style, etc) that dart_dev requires so that we can control which version of those it uses when running things like `pub run dart_dev format`.  So there's not a great solution for that that I can think of..

Just wanted to post this somewhere because it has already been helpful to me even in its current state, but it isn't really complete enough to incorporate IMO.

**Comment by zoechi** [comment]
There was also some work done on `pub` https://github.com/dart-lang/pub/pull/1515 (some discussion also in https://github.com/dart-lang/pub/pull/1508, https://github.com/dart-lang/pub/issues/343)

**Comment by travissanderson-wf** [comment]
Nice!
